import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// const axios = require('axios');

export default function Home({ data }) {
	return (
		<div className={styles.container}>
			{/* {console.log(data)} */}
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Bienvenido <a href="#">{data.data.nombre}</a>
				</h1>

				<p className={styles.description}>
					Su edad es
					<code className={styles.code}>{data.data.edad}</code>
				</p>

				<div className={styles.grid}>
					<a href="#" className={styles.card}>
						<h2>Documento &rarr;</h2>
						<p>DNI</p>
						<p>{data.data.dni}</p>
					</a>

					<a href="https://nextjs.org/learn" className={styles.card}>
						<h2>Learn &rarr;</h2>
						<p>Learn about Next.js in an interactive course with quizzes!</p>
					</a>

					<a
						href="https://github.com/vercel/next.js/tree/canary/examples"
						className={styles.card}
					>
						<h2>Examples &rarr;</h2>
						<p>Discover and deploy boilerplate example Next.js projects.</p>
					</a>

					<a
						href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						className={styles.card}
					>
						<h2>Deploy &rarr;</h2>
						<p>
							Instantly deploy your Next.js site to a public URL with Vercel.
						</p>
					</a>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}


export const getServerSideProps = async () => {
	
	
	  // const r1 = await fetch("http://0.0.0.0:8000/api/usuarios/123")
	//   console.log('Giordan - '+process.env.NEXTJS_APP_REST);
	//   console.log('Giordan 2 - '+process.env.PORT);
	  // const r1 = await fetch("http://0.0.0.0:80/api/usuarios/123")
	  // FetchError: request to http://0.0.0.0/api/usuarios/123 failed, reason: connect ECONNREFUSED 0.0.0.0:80
		
		const response = await fetch("http://nodejsapp:6000/api/usuarios/123");
		const data = await response.json();
	
		return { props: { data } };


















	// const r1 = await fetch("http://0.0.0.0:8000/api/usuarios/123")
	// console.log("Giordan - " + process.env.NEXTJS_APP_REST);
	// const r1 = await fetch("http://0.0.0.0:80/api/usuarios/123")
	// FetchError: request to http://0.0.0.0/api/usuarios/123 failed, reason: connect ECONNREFUSED 0.0.0.0:80
	// let data = ''
	// try {
	// 	const result = await axios({
	// 		method: "GET",
	// 		url: process.env.NEXTJS_APP_REST + "/usuarios/123",
	// 	});
	// 	data = result.data;
	// 	// console.log(result);
	
	// } catch (error) {
	// 	console.log(error);
	// }
	// try {
	// 	const r2 = await axios({
	// 		method: "GET",
	// 		url: "http://localhost/api/usuarios/123",
	// 	});
	// 	data = r2.data;
	// 	// console.log(r2);
	
	// } catch (error) {
	// 	console.log(error);
	// }
	// try {
	// 	const r3 = await axios({


};